import React from 'react';
import { Eye, Image as ImageIcon, Sparkles, Activity, Layers } from 'lucide-react';
import { VisualEvidence } from '../types';

interface EvidenceViewerProps {
  visualization?: VisualEvidence | string | null;
  loading: boolean;
}

export const EvidenceViewer: React.FC<EvidenceViewerProps> = ({
  visualization,
  loading,
}) => {
  if (loading) {
    return (
      <div className="card evidence-card loading">
        <div className="card-header">
          <div className="card-title-group">
            <h2 className="card-title">Visual Evidence & Spatial Overlays</h2>
            <span className="card-hint">Generating geospatial heatmaps or difference masks...</span>
          </div>
        </div>
        <div className="evidence-placeholder">
          <div className="pulse-loader"></div>
          <p className="placeholder-text">Synthesizing spatial overlay raster...</p>
        </div>
      </div>
    );
  }

  // Normalization: visualization could be string or object
  let vizObject: VisualEvidence | null = null;
  if (typeof visualization === 'string') {
    vizObject = {
      title: 'Geospatial Visual Overlay',
      url: visualization,
      description: 'Visual evidence generated by the spatial specialist model.',
    };
  } else if (visualization && typeof visualization === 'object') {
    vizObject = visualization;
  }

  return (
    <div className="card evidence-card">
      <div className="card-header">
        <div className="card-title-group">
          <div className="status-indicator-badge">
            <Eye size={16} className="text-cyan" />
            <h2 className="card-title">Visual Evidence & Spatial Overlays</h2>
          </div>
          <span className="card-hint">Optional spatial heatmaps, segmentation masks, or difference rasters</span>
        </div>
        {vizObject && (
          <span className="badge-tag">
            <Sparkles size={12} /> {vizObject.type ? vizObject.type.toUpperCase() : 'VISUAL EVIDENCE'}
          </span>
        )}
      </div>

      {vizObject ? (
        <div className="evidence-content">
          <div className="evidence-header-info">
            <h4 className="evidence-title">{vizObject.title || 'Spatial Analysis Evidence'}</h4>
            {vizObject.description && (
              <p className="evidence-description">{vizObject.description}</p>
            )}
          </div>

          {/* If there is an image/url/base64 */}
          {(vizObject.url || vizObject.base64) ? (
            <div className="evidence-image-container">
              <img
                src={vizObject.url || vizObject.base64}
                alt="Visual Evidence Overlay"
                className="evidence-image"
              />
            </div>
          ) : (
            /* Visual mock raster preview for simulation */
            <div className="synthetic-overlay-box">
              <div className="synthetic-grid-canvas">
                <div className="grid-overlay-lines"></div>
                <div className="synthetic-heatmap-spot spot-1"></div>
                <div className="synthetic-heatmap-spot spot-2"></div>
                <div className="synthetic-annotation-box">
                  <span className="annotation-tag">Detected Alteration Zone A (89% Conf)</span>
                </div>
              </div>
              <div className="synthetic-caption">
                <Layers size={13} /> Geospatial Attention / Change Layer rendered by model
              </div>
            </div>
          )}

          {/* Spatial Metrics if provided */}
          {vizObject.metrics && Object.keys(vizObject.metrics).length > 0 && (
            <div className="evidence-metrics-grid">
              {Object.entries(vizObject.metrics).map(([key, val], idx) => (
                <div key={idx} className="evidence-metric-item">
                  <span className="metric-key">{key}</span>
                  <span className="metric-val">{String(val)}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      ) : (
        /* Clean Empty State */
        <div className="evidence-empty-state">
          <div className="empty-state-box">
            <div className="empty-icon-wrapper">
              <ImageIcon size={32} className="text-muted" />
            </div>
            <h4 className="empty-title">No Visual Overlay Generated</h4>
            <p className="empty-desc">
              Visual evidence, difference masks, or heatmaps will dynamically render here when provided by the backend spatial model.
            </p>
            <div className="empty-tags">
              <span className="empty-tag"><Activity size={11} /> Supports GeoTIFF heatmaps</span>
              <span className="empty-tag"><Layers size={11} /> Bi-temporal change masks</span>
              <span className="empty-tag"><Eye size={11} /> Polarimetric SAR overlays</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
